name: spotify_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.0.10+1
  get_it: ^8.2.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
